version: "2"

services:
  train-gpu:
    image: tensorflow/tensorflow:2.11.0-gpu
    volumes:
      - ${REPO_DIR}:/code
    command: python /code/train.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  train-cpu:
    image: tensorflow/tensorflow:2.11.0
    volumes:
      - ${REPO_DIR}:/code
    command: python /code/train.py
